#!/usr/bin/env python
# -*- encoding: utf-8 -*-

ERR_SUCCESS = 0
MSG_SUCCESS = 'success'
ERR_FAILURE = 1
MSG_FAILURE = 'failure'
ERR_INVALID_PARAMS = 2
MSG_INVALID_PARAMS = 'invalid_params'
ERR_INTERNAL_ERROR = 3
MSG_INTERNAL_ERROR = 'invalid_msg'
ERR_UNKNOWN_ERROR = 4
MSG_UNKNOWN_ERROR = 'unknown_msg'

ERR_TRACE_INVALID_EVENT = 10
MSG_TRACE_INVALID_EVENT = 'invalid_event'

ERR_CID_NO_CATEGORY = 20
MSG_CID_NO_CATEGORY = 'no_category'

ERR_AD_QPS_LIMIT = 30
MSG_AD_QPS_LIMIT = 'qps_limit'
ERR_AD_QPS_ERROR = 31
MSG_AD_QPS_ERROR = 'qps_error'
ERR_AD_SSP_ERROR = 32
MSG_AD_SSP_ERROR = 'ssp_error'

ERR_PRED_NO_AD = 40
MSG_PRED_NO_AD = 'no_ad'


EVENT_INVALID = -1
EVENT_DISPLAY = 0
EVENT_CLICK_AD = 1
EVENT_DISPLAY_DURATION = 2


LIMIT_ALLOW = '0'
LIMIT_QPS_REFUSE = '1'
